// Importing Libraries
import Head from 'next/head'
import {promises as fs} from 'fs';
// Importing Components
import Heading from './components/Heading'
import SelectedProject from './components/Project'
import GradientImage from './components/GradientImage'
import Banner from './components/Banner'
import MyTimeline from './components/MyTimeline'
import Footer from './components/Footer'
import Navbar from './components/Navbar'
// Importing data and images
import myImage from '../public/myImage.png'

export default async function Home() {
  const file = await fs.readFile(process.cwd() + '/_data/data.json', 'utf-8')
  const data = JSON.parse(file);
  return (
    <div>
      <Head>
        <title>NishSpace</title>
        <meta name='description' content='Generated by Anish tatke'></meta>
        <link rel='icon'></link>
      </Head>

      <main className='bg-board h-max font-exo2 tracking-wide'>
        <Navbar />
        <section className='px-3 h-full'>
          <div id='intro' className='flex px-3'>
            <div className='w-1/2 h-fit px-5 py-10 text-center self-center'>
              <h3 className='py-3'>Hey, I am ...</h3>
              <h2 className='py-3 text-7xl font-kaushanScript'>Anish Tatke</h2>
              <p className='pt-2 pb-5 leading-relaxed'>I am a software developer passionate about machine learning. I am currently a Masters student at University of Florida. I aspire to learn, evolve and use the power of Artificial Intelligence to make the world a better place.</p>
            </div>
            <div className='flex w-1/2 h-fit px-5 pt-10 justify-center'>
              <GradientImage
                priority
                image={myImage}
                containerClass="relative w-[485px] h-[518px] overflow-hidden"
                maskClass="absolute z-10 h-full w-full bg-[linear-gradient(180deg,rgba(30,30,30,0)_0%,rgba(30,30,30,0.77)_75.71%,rgba(30,30,30,0.87)_86.59%,rgba(30,30,30,1)_100%)]"
              />
            </div>
          </div>

          <div id='projects' className='w-full'>
            <Heading>Projects</Heading>
            <SelectedProject projects={data.projects} />
          </div>

          <div id='profile' className='w-full'>
            <Heading>Profile</Heading>
            <div className='w-11/12 left-0 right-0 mx-auto my-5 flex flex-row'>
              <Banner style="p-1 w-1/3" data={{ title: "Bio Data", content: data.biodata }} />
              <Banner style="p-1 w-1/3" data={{ title: "Skills", content: data.skills }} />
            </div>

            <div className='relative w-full h-full px-2 my-20 left-0 right-0 mx-auto'>
              <MyTimeline events={data.events} />
            </div>
          </div>
        </section>
        <Footer links={data.links} resume={data.resume}/>
      </main>
    </div>
  )
}
